// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: rpcapi/auth1.proto

package rpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteJwtSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
}

func (x *SiteJwtSecretRequest) Reset() {
	*x = SiteJwtSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteJwtSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteJwtSecretRequest) ProtoMessage() {}

func (x *SiteJwtSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteJwtSecretRequest.ProtoReflect.Descriptor instead.
func (*SiteJwtSecretRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{0}
}

func (x *SiteJwtSecretRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

type SiteJwtSecretReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtSecret []byte `protobuf:"bytes,1,opt,name=jwtSecret,proto3" json:"jwtSecret,omitempty"`
}

func (x *SiteJwtSecretReply) Reset() {
	*x = SiteJwtSecretReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteJwtSecretReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteJwtSecretReply) ProtoMessage() {}

func (x *SiteJwtSecretReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteJwtSecretReply.ProtoReflect.Descriptor instead.
func (*SiteJwtSecretReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{1}
}

func (x *SiteJwtSecretReply) GetJwtSecret() []byte {
	if x != nil {
		return x.JwtSecret
	}
	return nil
}

type LoginUidpwRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	Ver     string `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Uid     string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pw      []byte `protobuf:"bytes,4,opt,name=pw,proto3" json:"pw,omitempty"`
}

func (x *LoginUidpwRequest) Reset() {
	*x = LoginUidpwRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginUidpwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUidpwRequest) ProtoMessage() {}

func (x *LoginUidpwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUidpwRequest.ProtoReflect.Descriptor instead.
func (*LoginUidpwRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUidpwRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *LoginUidpwRequest) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *LoginUidpwRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginUidpwRequest) GetPw() []byte {
	if x != nil {
		return x.Pw
	}
	return nil
}

type LoginResultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atk string `protobuf:"bytes,1,opt,name=atk,proto3" json:"atk,omitempty"`
	Rtk string `protobuf:"bytes,2,opt,name=rtk,proto3" json:"rtk,omitempty"`
}

func (x *LoginResultReply) Reset() {
	*x = LoginResultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResultReply) ProtoMessage() {}

func (x *LoginResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResultReply.ProtoReflect.Descriptor instead.
func (*LoginResultReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResultReply) GetAtk() string {
	if x != nil {
		return x.Atk
	}
	return ""
}

func (x *LoginResultReply) GetRtk() string {
	if x != nil {
		return x.Rtk
	}
	return ""
}

type RtokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	Rtk     string `protobuf:"bytes,2,opt,name=rtk,proto3" json:"rtk,omitempty"`
}

func (x *RtokenRequest) Reset() {
	*x = RtokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtokenRequest) ProtoMessage() {}

func (x *RtokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtokenRequest.ProtoReflect.Descriptor instead.
func (*RtokenRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{4}
}

func (x *RtokenRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *RtokenRequest) GetRtk() string {
	if x != nil {
		return x.Rtk
	}
	return ""
}

type LogoutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{5}
}

type UserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type UserInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey  string                      `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
	Nick     string                      `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Email    string                      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Photo    string                      `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"` //optional name = 5;
	Blocked  bool                        `protobuf:"varint,10,opt,name=blocked,proto3" json:"blocked,omitempty"`
	JoinedAt int32                       `protobuf:"varint,11,opt,name=joinedAt,proto3" json:"joinedAt,omitempty"`
	Extras   []*UserInfoReply_ExtraField `protobuf:"bytes,99,rep,name=extras,proto3" json:"extras,omitempty"`
}

func (x *UserInfoReply) Reset() {
	*x = UserInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReply) ProtoMessage() {}

func (x *UserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReply.ProtoReflect.Descriptor instead.
func (*UserInfoReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoReply) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *UserInfoReply) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserInfoReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoReply) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *UserInfoReply) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *UserInfoReply) GetJoinedAt() int32 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *UserInfoReply) GetExtras() []*UserInfoReply_ExtraField {
	if x != nil {
		return x.Extras
	}
	return nil
}

type AddSiteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	Uid     string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pw      []byte `protobuf:"bytes,4,opt,name=pw,proto3" json:"pw,omitempty"`
	Memo    string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (x *AddSiteUserRequest) Reset() {
	*x = AddSiteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSiteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSiteUserRequest) ProtoMessage() {}

func (x *AddSiteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSiteUserRequest.ProtoReflect.Descriptor instead.
func (*AddSiteUserRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{8}
}

func (x *AddSiteUserRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *AddSiteUserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddSiteUserRequest) GetPw() []byte {
	if x != nil {
		return x.Pw
	}
	return nil
}

func (x *AddSiteUserRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type AddSiteUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
}

func (x *AddSiteUserReply) Reset() {
	*x = AddSiteUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSiteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSiteUserReply) ProtoMessage() {}

func (x *AddSiteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSiteUserReply.ProtoReflect.Descriptor instead.
func (*AddSiteUserReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{9}
}

func (x *AddSiteUserReply) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type UserInfoReply_ExtraField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UserInfoReply_ExtraField) Reset() {
	*x = UserInfoReply_ExtraField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoReply_ExtraField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReply_ExtraField) ProtoMessage() {}

func (x *UserInfoReply_ExtraField) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReply_ExtraField.ProtoReflect.Descriptor instead.
func (*UserInfoReply_ExtraField) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UserInfoReply_ExtraField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserInfoReply_ExtraField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_rpcapi_auth1_proto protoreflect.FileDescriptor

var file_rpcapi_auth1_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x22, 0x30, 0x0a, 0x14,
	0x53, 0x69, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x32,
	0x0a, 0x12, 0x53, 0x69, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x22, 0x61, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x70, 0x77,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x70, 0x77, 0x22, 0x36, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x74, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x74, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x74, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x74, 0x6b, 0x22, 0x3b, 0x0a,
	0x0d, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x74, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x74, 0x6b, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x0a, 0x0f, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x8f, 0x02, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x73, 0x18, 0x63, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x73, 0x1a, 0x34, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x64, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53,
	0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x77,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65,
	0x6d, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x22, 0x2c,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x32, 0xa2, 0x03, 0x0a,
	0x05, 0x41, 0x75, 0x74, 0x68, 0x31, 0x12, 0x4e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x74,
	0x65, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x72, 0x70, 0x63,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55,
	0x69, 0x64, 0x70, 0x77, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x70, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x0a, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x41, 0x64,
	0x64, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcapi_auth1_proto_rawDescOnce sync.Once
	file_rpcapi_auth1_proto_rawDescData = file_rpcapi_auth1_proto_rawDesc
)

func file_rpcapi_auth1_proto_rawDescGZIP() []byte {
	file_rpcapi_auth1_proto_rawDescOnce.Do(func() {
		file_rpcapi_auth1_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcapi_auth1_proto_rawDescData)
	})
	return file_rpcapi_auth1_proto_rawDescData
}

var file_rpcapi_auth1_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpcapi_auth1_proto_goTypes = []interface{}{
	(*SiteJwtSecretRequest)(nil),     // 0: rpcapi.SiteJwtSecretRequest
	(*SiteJwtSecretReply)(nil),       // 1: rpcapi.SiteJwtSecretReply
	(*LoginUidpwRequest)(nil),        // 2: rpcapi.LoginUidpwRequest
	(*LoginResultReply)(nil),         // 3: rpcapi.LoginResultReply
	(*RtokenRequest)(nil),            // 4: rpcapi.RtokenRequest
	(*LogoutReply)(nil),              // 5: rpcapi.LogoutReply
	(*UserInfoRequest)(nil),          // 6: rpcapi.UserInfoRequest
	(*UserInfoReply)(nil),            // 7: rpcapi.UserInfoReply
	(*AddSiteUserRequest)(nil),       // 8: rpcapi.AddSiteUserRequest
	(*AddSiteUserReply)(nil),         // 9: rpcapi.AddSiteUserReply
	(*UserInfoReply_ExtraField)(nil), // 10: rpcapi.UserInfoReply.ExtraField
}
var file_rpcapi_auth1_proto_depIdxs = []int32{
	10, // 0: rpcapi.UserInfoReply.extras:type_name -> rpcapi.UserInfoReply.ExtraField
	0,  // 1: rpcapi.Auth1.GetSiteJwtSecret:input_type -> rpcapi.SiteJwtSecretRequest
	2,  // 2: rpcapi.Auth1.LoginUidpw:input_type -> rpcapi.LoginUidpwRequest
	4,  // 3: rpcapi.Auth1.RefreshUser:input_type -> rpcapi.RtokenRequest
	4,  // 4: rpcapi.Auth1.LogoutUser:input_type -> rpcapi.RtokenRequest
	6,  // 5: rpcapi.Auth1.GetUserInfo:input_type -> rpcapi.UserInfoRequest
	8,  // 6: rpcapi.Auth1.AddSiteUser:input_type -> rpcapi.AddSiteUserRequest
	1,  // 7: rpcapi.Auth1.GetSiteJwtSecret:output_type -> rpcapi.SiteJwtSecretReply
	3,  // 8: rpcapi.Auth1.LoginUidpw:output_type -> rpcapi.LoginResultReply
	3,  // 9: rpcapi.Auth1.RefreshUser:output_type -> rpcapi.LoginResultReply
	5,  // 10: rpcapi.Auth1.LogoutUser:output_type -> rpcapi.LogoutReply
	7,  // 11: rpcapi.Auth1.GetUserInfo:output_type -> rpcapi.UserInfoReply
	9,  // 12: rpcapi.Auth1.AddSiteUser:output_type -> rpcapi.AddSiteUserReply
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rpcapi_auth1_proto_init() }
func file_rpcapi_auth1_proto_init() {
	if File_rpcapi_auth1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcapi_auth1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteJwtSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteJwtSecretReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginUidpwRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSiteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSiteUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoReply_ExtraField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcapi_auth1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcapi_auth1_proto_goTypes,
		DependencyIndexes: file_rpcapi_auth1_proto_depIdxs,
		MessageInfos:      file_rpcapi_auth1_proto_msgTypes,
	}.Build()
	File_rpcapi_auth1_proto = out.File
	file_rpcapi_auth1_proto_rawDesc = nil
	file_rpcapi_auth1_proto_goTypes = nil
	file_rpcapi_auth1_proto_depIdxs = nil
}
