// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: rpcapi/auth1.proto

package rpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JwtSecretRequest) Reset() {
	*x = JwtSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtSecretRequest) ProtoMessage() {}

func (x *JwtSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtSecretRequest.ProtoReflect.Descriptor instead.
func (*JwtSecretRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{0}
}

type JwtSecretReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JwtSecret []byte `protobuf:"bytes,1,opt,name=jwtSecret,proto3" json:"jwtSecret,omitempty"`
	TenantKey string `protobuf:"bytes,2,opt,name=tenantKey,proto3" json:"tenantKey,omitempty"`
	TenantId  int32  `protobuf:"varint,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	SiteKey   string `protobuf:"bytes,4,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	SiteId    int32  `protobuf:"varint,5,opt,name=siteId,proto3" json:"siteId,omitempty"`
}

func (x *JwtSecretReply) Reset() {
	*x = JwtSecretReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtSecretReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtSecretReply) ProtoMessage() {}

func (x *JwtSecretReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtSecretReply.ProtoReflect.Descriptor instead.
func (*JwtSecretReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{1}
}

func (x *JwtSecretReply) GetJwtSecret() []byte {
	if x != nil {
		return x.JwtSecret
	}
	return nil
}

func (x *JwtSecretReply) GetTenantKey() string {
	if x != nil {
		return x.TenantKey
	}
	return ""
}

func (x *JwtSecretReply) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *JwtSecretReply) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *JwtSecretReply) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type LoginUidpwRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	SiteId  int32  `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Uid     string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pw      []byte `protobuf:"bytes,4,opt,name=pw,proto3" json:"pw,omitempty"`
}

func (x *LoginUidpwRequest) Reset() {
	*x = LoginUidpwRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginUidpwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUidpwRequest) ProtoMessage() {}

func (x *LoginUidpwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUidpwRequest.ProtoReflect.Descriptor instead.
func (*LoginUidpwRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUidpwRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *LoginUidpwRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *LoginUidpwRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginUidpwRequest) GetPw() []byte {
	if x != nil {
		return x.Pw
	}
	return nil
}

type LoginAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pw  []byte `protobuf:"bytes,4,opt,name=pw,proto3" json:"pw,omitempty"`
}

func (x *LoginAdminRequest) Reset() {
	*x = LoginAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminRequest) ProtoMessage() {}

func (x *LoginAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminRequest.ProtoReflect.Descriptor instead.
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{3}
}

func (x *LoginAdminRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginAdminRequest) GetPw() []byte {
	if x != nil {
		return x.Pw
	}
	return nil
}

type LoginOneTapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	SiteId  int32  `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginOneTapRequest) Reset() {
	*x = LoginOneTapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginOneTapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOneTapRequest) ProtoMessage() {}

func (x *LoginOneTapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOneTapRequest.ProtoReflect.Descriptor instead.
func (*LoginOneTapRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{4}
}

func (x *LoginOneTapRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *LoginOneTapRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *LoginOneTapRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atk string `protobuf:"bytes,1,opt,name=atk,proto3" json:"atk,omitempty"`
	Rtk string `protobuf:"bytes,2,opt,name=rtk,proto3" json:"rtk,omitempty"`
}

func (x *LoginResultReply) Reset() {
	*x = LoginResultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResultReply) ProtoMessage() {}

func (x *LoginResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResultReply.ProtoReflect.Descriptor instead.
func (*LoginResultReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResultReply) GetAtk() string {
	if x != nil {
		return x.Atk
	}
	return ""
}

func (x *LoginResultReply) GetRtk() string {
	if x != nil {
		return x.Rtk
	}
	return ""
}

type RtokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rtk string `protobuf:"bytes,2,opt,name=rtk,proto3" json:"rtk,omitempty"`
}

func (x *RtokenRequest) Reset() {
	*x = RtokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtokenRequest) ProtoMessage() {}

func (x *RtokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtokenRequest.ProtoReflect.Descriptor instead.
func (*RtokenRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{6}
}

func (x *RtokenRequest) GetRtk() string {
	if x != nil {
		return x.Rtk
	}
	return ""
}

type LogoutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{7}
}

type UserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfoRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type UserInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey  string                      `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
	Nick     string                      `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Email    string                      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Photo    string                      `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"` //optional name = 5;
	Blocked  bool                        `protobuf:"varint,10,opt,name=blocked,proto3" json:"blocked,omitempty"`
	JoinedAt int32                       `protobuf:"varint,11,opt,name=joinedAt,proto3" json:"joinedAt,omitempty"`
	Extras   []*UserInfoReply_ExtraField `protobuf:"bytes,99,rep,name=extras,proto3" json:"extras,omitempty"`
}

func (x *UserInfoReply) Reset() {
	*x = UserInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReply) ProtoMessage() {}

func (x *UserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReply.ProtoReflect.Descriptor instead.
func (*UserInfoReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfoReply) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *UserInfoReply) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserInfoReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoReply) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *UserInfoReply) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *UserInfoReply) GetJoinedAt() int32 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *UserInfoReply) GetExtras() []*UserInfoReply_ExtraField {
	if x != nil {
		return x.Extras
	}
	return nil
}

type AddSiteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	SiteId  int32  `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Uid     string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Pw      []byte `protobuf:"bytes,4,opt,name=pw,proto3" json:"pw,omitempty"`
	Memo    string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (x *AddSiteUserRequest) Reset() {
	*x = AddSiteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSiteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSiteUserRequest) ProtoMessage() {}

func (x *AddSiteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSiteUserRequest.ProtoReflect.Descriptor instead.
func (*AddSiteUserRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{10}
}

func (x *AddSiteUserRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *AddSiteUserRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *AddSiteUserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddSiteUserRequest) GetPw() []byte {
	if x != nil {
		return x.Pw
	}
	return nil
}

func (x *AddSiteUserRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type AddSiteUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
}

func (x *AddSiteUserReply) Reset() {
	*x = AddSiteUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSiteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSiteUserReply) ProtoMessage() {}

func (x *AddSiteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSiteUserReply.ProtoReflect.Descriptor instead.
func (*AddSiteUserReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{11}
}

func (x *AddSiteUserReply) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type SetUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string  `protobuf:"bytes,3,opt,name=userKey,proto3" json:"userKey,omitempty"`
	Nick    *string `protobuf:"bytes,4,opt,name=nick,proto3,oneof" json:"nick,omitempty"`
	Email   *string `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
}

func (x *SetUserInfoRequest) Reset() {
	*x = SetUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserInfoRequest) ProtoMessage() {}

func (x *SetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*SetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserInfoRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *SetUserInfoRequest) GetNick() string {
	if x != nil && x.Nick != nil {
		return *x.Nick
	}
	return ""
}

func (x *SetUserInfoRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type SetUserInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,1,opt,name=userKey,proto3" json:"userKey,omitempty"`
}

func (x *SetUserInfoReply) Reset() {
	*x = SetUserInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserInfoReply) ProtoMessage() {}

func (x *SetUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserInfoReply.ProtoReflect.Descriptor instead.
func (*SetUserInfoReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserInfoReply) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

type SetUserPwRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,3,opt,name=userKey,proto3" json:"userKey,omitempty"`
	PwOld   []byte `protobuf:"bytes,4,opt,name=pwOld,proto3" json:"pwOld,omitempty"`
	PwNew   []byte `protobuf:"bytes,5,opt,name=pwNew,proto3" json:"pwNew,omitempty"`
}

func (x *SetUserPwRequest) Reset() {
	*x = SetUserPwRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserPwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPwRequest) ProtoMessage() {}

func (x *SetUserPwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPwRequest.ProtoReflect.Descriptor instead.
func (*SetUserPwRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{14}
}

func (x *SetUserPwRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *SetUserPwRequest) GetPwOld() []byte {
	if x != nil {
		return x.PwOld
	}
	return nil
}

func (x *SetUserPwRequest) GetPwNew() []byte {
	if x != nil {
		return x.PwNew
	}
	return nil
}

type SetUserPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKey string `protobuf:"bytes,3,opt,name=userKey,proto3" json:"userKey,omitempty"`
	Url     string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SetUserPhotoRequest) Reset() {
	*x = SetUserPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPhotoRequest) ProtoMessage() {}

func (x *SetUserPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPhotoRequest.ProtoReflect.Descriptor instead.
func (*SetUserPhotoRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{15}
}

func (x *SetUserPhotoRequest) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *SetUserPhotoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Memo    string `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (x *CreateSiteRequest) Reset() {
	*x = CreateSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteRequest) ProtoMessage() {}

func (x *CreateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSiteRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *CreateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type CreateSiteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId int32 `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
}

func (x *CreateSiteReply) Reset() {
	*x = CreateSiteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSiteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteReply) ProtoMessage() {}

func (x *CreateSiteReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteReply.ProtoReflect.Descriptor instead.
func (*CreateSiteReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{17}
}

func (x *CreateSiteReply) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type SetUidpwPvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey  string `protobuf:"bytes,1,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
	SiteId   int32  `protobuf:"varint,2,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Disabled bool   `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
}

func (x *SetUidpwPvRequest) Reset() {
	*x = SetUidpwPvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUidpwPvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUidpwPvRequest) ProtoMessage() {}

func (x *SetUidpwPvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUidpwPvRequest.ProtoReflect.Descriptor instead.
func (*SetUidpwPvRequest) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{18}
}

func (x *SetUidpwPvRequest) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *SetUidpwPvRequest) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *SetUidpwPvRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type SetUidpwPvReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetUidpwPvReply) Reset() {
	*x = SetUidpwPvReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUidpwPvReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUidpwPvReply) ProtoMessage() {}

func (x *SetUidpwPvReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUidpwPvReply.ProtoReflect.Descriptor instead.
func (*SetUidpwPvReply) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{19}
}

type UserInfoReply_ExtraField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UserInfoReply_ExtraField) Reset() {
	*x = UserInfoReply_ExtraField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcapi_auth1_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoReply_ExtraField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReply_ExtraField) ProtoMessage() {}

func (x *UserInfoReply_ExtraField) ProtoReflect() protoreflect.Message {
	mi := &file_rpcapi_auth1_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReply_ExtraField.ProtoReflect.Descriptor instead.
func (*UserInfoReply_ExtraField) Descriptor() ([]byte, []int) {
	return file_rpcapi_auth1_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UserInfoReply_ExtraField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserInfoReply_ExtraField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_rpcapi_auth1_proto protoreflect.FileDescriptor

var file_rpcapi_auth1_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x22, 0x12, 0x0a, 0x10,
	0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0x67, 0x0a,
	0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x70, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x77, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x02, 0x70, 0x77, 0x22, 0x35, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x77, 0x22, 0x5c, 0x0a,
	0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x6e, 0x65, 0x54, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x36, 0x0a, 0x10, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x74, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x74,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x74, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x74, 0x6b, 0x22, 0x21, 0x0a, 0x0d, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x74, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x74, 0x6b, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x22, 0x8f, 0x02, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69,
	0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x73, 0x18, 0x63,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x73, 0x1a, 0x34,
	0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x7c, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x70, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x70, 0x77, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65,
	0x6d, 0x6f, 0x22, 0x2c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x22, 0x75, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x12, 0x17, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2c, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x58, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x77, 0x4f, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x70, 0x77, 0x4f, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x77, 0x4e,
	0x65, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x77, 0x4e, 0x65, 0x77, 0x22,
	0x41, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x55, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69,
	0x74, 0x65, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x55, 0x69, 0x64, 0x70, 0x77,
	0x50, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x55, 0x69,
	0x64, 0x70, 0x77, 0x50, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xfd, 0x07, 0x0a, 0x05, 0x41,
	0x75, 0x74, 0x68, 0x31, 0x12, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4a, 0x77, 0x74, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x77,
	0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x55, 0x69, 0x64, 0x70, 0x77, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x70, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x6e, 0x65, 0x54, 0x61, 0x70, 0x12, 0x1a, 0x2e, 0x72,
	0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x6e, 0x65, 0x54, 0x61,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63,
	0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x53,
	0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x69, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x77, 0x12, 0x18,
	0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x19, 0x2e, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x42, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x74, 0x65,
	0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x55, 0x69, 0x64,
	0x70, 0x77, 0x50, 0x56, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x74, 0x55, 0x69, 0x64, 0x70, 0x77, 0x50, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x69, 0x64, 0x70,
	0x77, 0x50, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcapi_auth1_proto_rawDescOnce sync.Once
	file_rpcapi_auth1_proto_rawDescData = file_rpcapi_auth1_proto_rawDesc
)

func file_rpcapi_auth1_proto_rawDescGZIP() []byte {
	file_rpcapi_auth1_proto_rawDescOnce.Do(func() {
		file_rpcapi_auth1_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcapi_auth1_proto_rawDescData)
	})
	return file_rpcapi_auth1_proto_rawDescData
}

var file_rpcapi_auth1_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_rpcapi_auth1_proto_goTypes = []interface{}{
	(*JwtSecretRequest)(nil),         // 0: rpcapi.JwtSecretRequest
	(*JwtSecretReply)(nil),           // 1: rpcapi.JwtSecretReply
	(*LoginUidpwRequest)(nil),        // 2: rpcapi.LoginUidpwRequest
	(*LoginAdminRequest)(nil),        // 3: rpcapi.LoginAdminRequest
	(*LoginOneTapRequest)(nil),       // 4: rpcapi.LoginOneTapRequest
	(*LoginResultReply)(nil),         // 5: rpcapi.LoginResultReply
	(*RtokenRequest)(nil),            // 6: rpcapi.RtokenRequest
	(*LogoutReply)(nil),              // 7: rpcapi.LogoutReply
	(*UserInfoRequest)(nil),          // 8: rpcapi.UserInfoRequest
	(*UserInfoReply)(nil),            // 9: rpcapi.UserInfoReply
	(*AddSiteUserRequest)(nil),       // 10: rpcapi.AddSiteUserRequest
	(*AddSiteUserReply)(nil),         // 11: rpcapi.AddSiteUserReply
	(*SetUserInfoRequest)(nil),       // 12: rpcapi.SetUserInfoRequest
	(*SetUserInfoReply)(nil),         // 13: rpcapi.SetUserInfoReply
	(*SetUserPwRequest)(nil),         // 14: rpcapi.SetUserPwRequest
	(*SetUserPhotoRequest)(nil),      // 15: rpcapi.SetUserPhotoRequest
	(*CreateSiteRequest)(nil),        // 16: rpcapi.CreateSiteRequest
	(*CreateSiteReply)(nil),          // 17: rpcapi.CreateSiteReply
	(*SetUidpwPvRequest)(nil),        // 18: rpcapi.SetUidpwPvRequest
	(*SetUidpwPvReply)(nil),          // 19: rpcapi.SetUidpwPvReply
	(*UserInfoReply_ExtraField)(nil), // 20: rpcapi.UserInfoReply.ExtraField
}
var file_rpcapi_auth1_proto_depIdxs = []int32{
	20, // 0: rpcapi.UserInfoReply.extras:type_name -> rpcapi.UserInfoReply.ExtraField
	0,  // 1: rpcapi.Auth1.GetJwtSecret:input_type -> rpcapi.JwtSecretRequest
	2,  // 2: rpcapi.Auth1.LoginUidpw:input_type -> rpcapi.LoginUidpwRequest
	4,  // 3: rpcapi.Auth1.LoginOneTap:input_type -> rpcapi.LoginOneTapRequest
	6,  // 4: rpcapi.Auth1.RefreshUser:input_type -> rpcapi.RtokenRequest
	6,  // 5: rpcapi.Auth1.LogoutUser:input_type -> rpcapi.RtokenRequest
	8,  // 6: rpcapi.Auth1.GetUserInfo:input_type -> rpcapi.UserInfoRequest
	10, // 7: rpcapi.Auth1.AddSiteUser:input_type -> rpcapi.AddSiteUserRequest
	12, // 8: rpcapi.Auth1.SetUserInfo:input_type -> rpcapi.SetUserInfoRequest
	14, // 9: rpcapi.Auth1.SetUserPw:input_type -> rpcapi.SetUserPwRequest
	15, // 10: rpcapi.Auth1.SetUserPhoto:input_type -> rpcapi.SetUserPhotoRequest
	3,  // 11: rpcapi.Auth1.LoginAdmin:input_type -> rpcapi.LoginAdminRequest
	6,  // 12: rpcapi.Auth1.RefreshAdmin:input_type -> rpcapi.RtokenRequest
	6,  // 13: rpcapi.Auth1.LogoutAdmin:input_type -> rpcapi.RtokenRequest
	16, // 14: rpcapi.Auth1.CreateSite:input_type -> rpcapi.CreateSiteRequest
	18, // 15: rpcapi.Auth1.SetUidpwPV:input_type -> rpcapi.SetUidpwPvRequest
	1,  // 16: rpcapi.Auth1.GetJwtSecret:output_type -> rpcapi.JwtSecretReply
	5,  // 17: rpcapi.Auth1.LoginUidpw:output_type -> rpcapi.LoginResultReply
	5,  // 18: rpcapi.Auth1.LoginOneTap:output_type -> rpcapi.LoginResultReply
	5,  // 19: rpcapi.Auth1.RefreshUser:output_type -> rpcapi.LoginResultReply
	7,  // 20: rpcapi.Auth1.LogoutUser:output_type -> rpcapi.LogoutReply
	9,  // 21: rpcapi.Auth1.GetUserInfo:output_type -> rpcapi.UserInfoReply
	11, // 22: rpcapi.Auth1.AddSiteUser:output_type -> rpcapi.AddSiteUserReply
	13, // 23: rpcapi.Auth1.SetUserInfo:output_type -> rpcapi.SetUserInfoReply
	13, // 24: rpcapi.Auth1.SetUserPw:output_type -> rpcapi.SetUserInfoReply
	13, // 25: rpcapi.Auth1.SetUserPhoto:output_type -> rpcapi.SetUserInfoReply
	5,  // 26: rpcapi.Auth1.LoginAdmin:output_type -> rpcapi.LoginResultReply
	5,  // 27: rpcapi.Auth1.RefreshAdmin:output_type -> rpcapi.LoginResultReply
	7,  // 28: rpcapi.Auth1.LogoutAdmin:output_type -> rpcapi.LogoutReply
	17, // 29: rpcapi.Auth1.CreateSite:output_type -> rpcapi.CreateSiteReply
	19, // 30: rpcapi.Auth1.SetUidpwPV:output_type -> rpcapi.SetUidpwPvReply
	16, // [16:31] is the sub-list for method output_type
	1,  // [1:16] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rpcapi_auth1_proto_init() }
func file_rpcapi_auth1_proto_init() {
	if File_rpcapi_auth1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcapi_auth1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtSecretReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginUidpwRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginOneTapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSiteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSiteUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserPwRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSiteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUidpwPvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUidpwPvReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcapi_auth1_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoReply_ExtraField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpcapi_auth1_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcapi_auth1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcapi_auth1_proto_goTypes,
		DependencyIndexes: file_rpcapi_auth1_proto_depIdxs,
		MessageInfos:      file_rpcapi_auth1_proto_msgTypes,
	}.Build()
	File_rpcapi_auth1_proto = out.File
	file_rpcapi_auth1_proto_rawDesc = nil
	file_rpcapi_auth1_proto_goTypes = nil
	file_rpcapi_auth1_proto_depIdxs = nil
}
