// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: rpcapi/auth1.proto

package rpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Auth1Client is the client API for Auth1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Auth1Client interface {
	GetSiteJwtSecret(ctx context.Context, in *SiteJwtSecretRequest, opts ...grpc.CallOption) (*SiteJwtSecretReply, error)
	LoginUidpw(ctx context.Context, in *LoginUidpwRequest, opts ...grpc.CallOption) (*LoginResultReply, error)
	LoginOneTap(ctx context.Context, in *LoginOneTapRequest, opts ...grpc.CallOption) (*LoginResultReply, error)
	RefreshUser(ctx context.Context, in *RtokenRequest, opts ...grpc.CallOption) (*LoginResultReply, error)
	LogoutUser(ctx context.Context, in *RtokenRequest, opts ...grpc.CallOption) (*LogoutReply, error)
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoReply, error)
	AddSiteUser(ctx context.Context, in *AddSiteUserRequest, opts ...grpc.CallOption) (*AddSiteUserReply, error)
}

type auth1Client struct {
	cc grpc.ClientConnInterface
}

func NewAuth1Client(cc grpc.ClientConnInterface) Auth1Client {
	return &auth1Client{cc}
}

func (c *auth1Client) GetSiteJwtSecret(ctx context.Context, in *SiteJwtSecretRequest, opts ...grpc.CallOption) (*SiteJwtSecretReply, error) {
	out := new(SiteJwtSecretReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/GetSiteJwtSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auth1Client) LoginUidpw(ctx context.Context, in *LoginUidpwRequest, opts ...grpc.CallOption) (*LoginResultReply, error) {
	out := new(LoginResultReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/LoginUidpw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auth1Client) LoginOneTap(ctx context.Context, in *LoginOneTapRequest, opts ...grpc.CallOption) (*LoginResultReply, error) {
	out := new(LoginResultReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/LoginOneTap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auth1Client) RefreshUser(ctx context.Context, in *RtokenRequest, opts ...grpc.CallOption) (*LoginResultReply, error) {
	out := new(LoginResultReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/RefreshUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auth1Client) LogoutUser(ctx context.Context, in *RtokenRequest, opts ...grpc.CallOption) (*LogoutReply, error) {
	out := new(LogoutReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/LogoutUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auth1Client) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoReply, error) {
	out := new(UserInfoReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auth1Client) AddSiteUser(ctx context.Context, in *AddSiteUserRequest, opts ...grpc.CallOption) (*AddSiteUserReply, error) {
	out := new(AddSiteUserReply)
	err := c.cc.Invoke(ctx, "/rpcapi.Auth1/AddSiteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Auth1Server is the server API for Auth1 service.
// All implementations must embed UnimplementedAuth1Server
// for forward compatibility
type Auth1Server interface {
	GetSiteJwtSecret(context.Context, *SiteJwtSecretRequest) (*SiteJwtSecretReply, error)
	LoginUidpw(context.Context, *LoginUidpwRequest) (*LoginResultReply, error)
	LoginOneTap(context.Context, *LoginOneTapRequest) (*LoginResultReply, error)
	RefreshUser(context.Context, *RtokenRequest) (*LoginResultReply, error)
	LogoutUser(context.Context, *RtokenRequest) (*LogoutReply, error)
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfoReply, error)
	AddSiteUser(context.Context, *AddSiteUserRequest) (*AddSiteUserReply, error)
	mustEmbedUnimplementedAuth1Server()
}

// UnimplementedAuth1Server must be embedded to have forward compatible implementations.
type UnimplementedAuth1Server struct {
}

func (UnimplementedAuth1Server) GetSiteJwtSecret(context.Context, *SiteJwtSecretRequest) (*SiteJwtSecretReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteJwtSecret not implemented")
}
func (UnimplementedAuth1Server) LoginUidpw(context.Context, *LoginUidpwRequest) (*LoginResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUidpw not implemented")
}
func (UnimplementedAuth1Server) LoginOneTap(context.Context, *LoginOneTapRequest) (*LoginResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOneTap not implemented")
}
func (UnimplementedAuth1Server) RefreshUser(context.Context, *RtokenRequest) (*LoginResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshUser not implemented")
}
func (UnimplementedAuth1Server) LogoutUser(context.Context, *RtokenRequest) (*LogoutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogoutUser not implemented")
}
func (UnimplementedAuth1Server) GetUserInfo(context.Context, *UserInfoRequest) (*UserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAuth1Server) AddSiteUser(context.Context, *AddSiteUserRequest) (*AddSiteUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSiteUser not implemented")
}
func (UnimplementedAuth1Server) mustEmbedUnimplementedAuth1Server() {}

// UnsafeAuth1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Auth1Server will
// result in compilation errors.
type UnsafeAuth1Server interface {
	mustEmbedUnimplementedAuth1Server()
}

func RegisterAuth1Server(s grpc.ServiceRegistrar, srv Auth1Server) {
	s.RegisterService(&Auth1_ServiceDesc, srv)
}

func _Auth1_GetSiteJwtSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteJwtSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).GetSiteJwtSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/GetSiteJwtSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).GetSiteJwtSecret(ctx, req.(*SiteJwtSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth1_LoginUidpw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUidpwRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).LoginUidpw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/LoginUidpw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).LoginUidpw(ctx, req.(*LoginUidpwRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth1_LoginOneTap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginOneTapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).LoginOneTap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/LoginOneTap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).LoginOneTap(ctx, req.(*LoginOneTapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth1_RefreshUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RtokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).RefreshUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/RefreshUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).RefreshUser(ctx, req.(*RtokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth1_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RtokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/LogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).LogoutUser(ctx, req.(*RtokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth1_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth1_AddSiteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSiteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Auth1Server).AddSiteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcapi.Auth1/AddSiteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Auth1Server).AddSiteUser(ctx, req.(*AddSiteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth1_ServiceDesc is the grpc.ServiceDesc for Auth1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcapi.Auth1",
	HandlerType: (*Auth1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSiteJwtSecret",
			Handler:    _Auth1_GetSiteJwtSecret_Handler,
		},
		{
			MethodName: "LoginUidpw",
			Handler:    _Auth1_LoginUidpw_Handler,
		},
		{
			MethodName: "LoginOneTap",
			Handler:    _Auth1_LoginOneTap_Handler,
		},
		{
			MethodName: "RefreshUser",
			Handler:    _Auth1_RefreshUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _Auth1_LogoutUser_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Auth1_GetUserInfo_Handler,
		},
		{
			MethodName: "AddSiteUser",
			Handler:    _Auth1_AddSiteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcapi/auth1.proto",
}
